_BASE_: "Base-CenterNet.yaml"
DATASETS:
  TRAIN: ("coco_person_2017_train",)
  TEST: ("coco_person_2017_val",)
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  META_ARCHITECTURE: "CenterNet"
  BACKBONE:
    NAME: "build_torch_backbone"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res5"]
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  CENTERNET:
    DECONV_CHANNEL: [2048, 256, 128, 64]
    DECONV_KERNEL: [4, 4, 4]
    NUM_CLASSES: 1
    ENABLE_DCN: False
    MODULATE_DEFORM: True
    BIAS_VALUE: -2.19
    DOWN_SCALE: 4
    MIN_OVERLAP: 0.7
    TENSOR_DIM: 128
SOLVER:
  STEPS: (81000, 108000)
  MAX_ITER: 126000
  IMS_PER_BATCH: 128
  BASE_LR: 0.01 # Note that RetinaNet uses a different default learning rate
INPUT:
  FORMAT: 'RGB'
OUTPUT_DIR: ./logs/centernet-res50-without-dcn-person-only
